### ISSUE TITLE
Auch andere Settings denkbar?

### ISSUE THREAD

**Issue by LuleDZ** [Scepfari/SPACE1889-FVTT#20]
Ubiquity ist ein Universalsystem und es gibt viele Settings, die man damit bespielen kann. Space1889 ist eine. Daneben gibt es All for One und Hollow Earth Expedition um nur zwei weitere große zu nennen. Könnte man dieses System für Foundry um die andere Settings erweitern, ggf. mit Unterstützung?

**Comment by Scepfari** [comment]
Das Space System um die anderen Ubiquity Systeme zu erweitern ist schwierig, da ich beim Entwurf/Entwickeln ausschließlich auf Space geschaut habe und demzufolge Space spezifische Dinge fix in den Quellcode gesteckt habe. 
Erschwerend kommt hinzu das ich die anderen Systeme nicht kenne, All for One soll eine Zaubersystem haben, das ich aber nicht auf dem Charakterbogen (https://sites.google.com/site/ubiquityrpg/ubiquity/resources/character-sheets) entdecken kann. Wird das über die Talente abgebildet?
Anstatt am Space System herumzuflicken, wäre vermutlich das Erstellen eines eigenen Ubiquity Systems sinnvoller, also das Space System klonen und dann alles entfernen was nicht zu Ubiquity gehört. Muss ich mir noch überlegen, ob ich den Aufwand betreiben will...

**Comment by LuleDZ** [comment]
Herzlichen Dank für die Einschätzung.

AfO hat ein Zaubersystem, aber es ist den Spielenden meist nicht zugänglich, oder erst später. Wenn ich mich richtig erinnere, benötigt man ein Talent, damit man die entsprechende Fertigkeit (ich meine Okultes) auch zum Zaubern verwenden kann. Gerade in diesem Bereich gibt es aber große Unterschiede zwischen den Settings, ebenso wie beim Fahrzeugkampf, wenn ich das richtig überblicke. Aber auch das sind Bereiche, mit denen ich bisher nie gespielt habe. Magie kenne ich nur aus Desolation. Dort gibt es entsprechende Talente und eine eigene Fertigkeit.

Mal sehen, ob ich mich alleine an den Umbau traue. Ich habe bisher nur Erfahrungen mit Fantasy Grounds (FG), also xml und lua. Dort habe ich aber ein paar Systeme umgesetzt, auch Ubiquity, oder bei anderen mitgewirkt, bspw. DSA 4.1. Aber hat mir zu viele Hürden auf Spielendenseite und ich bin in der Nutzung nicht mehr glücklich geworden. Foundry macht da meiner Meinung nach vieles besser. Nur fehlt mir etwas für Ubiquity, insbesondere AfO-Setting. Nur finde ich den Einstieg nicht richtig. Die Tutorials scheinen veraltet. :-(

**Comment by Scepfari** [comment]
wenn du dem englischen mächtig bist empfehle ich auf jeden Fall den offiziellen Foundry Discord Channel der auch auf dieser Seite hier https://foundryvtt.wiki/en/development/guides/SD-tutorial verlinkt ist. Insbesondere auf dem [system-development ](https://discord.com/channels/170995199584108546/670336275496042502) Kanal wird einem kompetent geholfen, wenn man nicht weiterkommt. 
Da Space auf dem Boilerplate System (genauer, der Variante zu Foundry V9 Zeiten) basiert, ist auch der [Boilerplate System](https://discord.com/channels/170995199584108546/1222250400263176202) Kanal eine Anlaufstelle für Hilfe. 
Ich kann dir bei dem Projekt Starthilfe leisten und das Grundgerüst aufsetzen, Einzelheiten sollten wir direkt klären, ping mich am besten über Discord an (Scepfari#1283)
